spring:
  application:
    name: sample-application
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081

locale:
  language: ko_kr
  messages:
    encoding: UTF-8

logging:
  level:
    kr:
      co:
        wisenut: info

management:
  endpoints:
    web:
      exposure:
        include: "health,info"